name: Publish Release

on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'Release tag (format: vX.X.X)'
        required: true
        type: string

jobs:
  release:
    runs-on: [ self-hosted, linux, ARM64 ]

    env:
      TZ: "Asia/Hong_Kong"
      NODE_VERSION: "22.12.0"

    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          submodules: 'true'
          token: ${{ secrets.WRITE_REPO_PAT }}

      - name: Install Dependencies
        run: npm ci

      - name: Run Test
        run: npm test

      - name: Run Build
        run: npm run build

      - name: Update Package Version
        uses: yosemiteyss/update-package-version@v1.0.4
        with:
          runtime: node
          release_tag: ${{ github.event.inputs.release_tag }}
        env:
          WRITE_REPO_PAT: ${{ secrets.WRITE_REPO_PAT }}

      - name: Setup Version Name
        run: |
          VERSION_NAME=$(jq -r .version < package.json)
          echo "VERSION_NAME=$VERSION_NAME" >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.WRITE_PACKAGE_PAT }}

      - name: Build and Publish Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ env.VERSION_NAME }}
            ghcr.io/${{ github.repository }}:${{ env.VERSION_NAME }}-arm64
          platforms: linux/arm64

      - name: Create Release
        uses: softprops/action-gh-release@v2.2.1
        with:
          tag_name: ${{ github.event.inputs.release_tag }}
          token: ${{ secrets.WRITE_REPO_PAT }}
